// biome-ignore-all lint/performance/noNamespaceImport: autogenerated file
// biome-ignore-all lint/suspicious/noExplicitAny: autogenerated file
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  'button': {
    name: 'button',
    description: 'A button component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/button.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/button.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );

      return { default: mod[exportName] || mod.default };
    }),
    categories: undefined,
    meta: undefined,
  },
};
