// biome-ignore-all lint/performance/noNamespaceImport: autogenerated file
// biome-ignore-all lint/suspicious/noExplicitAny: autogenerated file
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

export const Index: Record<string, any> = {
  'button': {
    name: 'button',
    description: 'A button component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/button.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/button.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'accordion': {
    name: 'accordion',
    description: 'An accordion component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/accordion.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/accordion.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'avatar': {
    name: 'avatar',
    description: 'An avatar component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/avatar.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/avatar.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'badge': {
    name: 'badge',
    description: 'A badge component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/badge.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/badge.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'checkbox': {
    name: 'checkbox',
    description: 'A checkbox component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/checkbox.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/checkbox.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'dialog': {
    name: 'dialog',
    description: 'A dialog component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/dialog.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/dialog.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'command': {
    name: 'command',
    description: 'A command component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/dialog.tsx',
        type: 'registry:ui',
        target: '',
      },
      {
        path: 'registry/niv/ui/command.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/dialog.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'label': {
    name: 'label',
    description: 'A label component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/label.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/label.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'select': {
    name: 'select',
    description: 'A select component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/select.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/select.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'textarea': {
    name: 'textarea',
    description: 'A textarea component.',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/niv/ui/textarea.tsx',
        type: 'registry:ui',
        target: '',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/niv/ui/textarea.tsx');
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object',
      );
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
