catalog:
  "@biomejs/biome": 2.3.4
  "@commitlint/cli": 20.1.0
  "@commitlint/config-conventional": 20.0.0
  "@nivalis/biome-config": 2.3.4
  "@tailwindcss/postcss": 4.1.17
  "@total-typescript/ts-reset": 0.6.1
  "@types/mdx": 2.0.13
  "@types/node": 22.18.13
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  "@vercel/analytics": 1.5.0
  "@radix-ui/react-accordion": 1.2.12
  "@radix-ui/react-avatar": 1.1.11
  "@radix-ui/react-checkbox": 1.3.3
  "@radix-ui/react-dialog": 1.1.15
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-select": 2.2.6
  "@radix-ui/react-slider": 1.3.6
  "@radix-ui/react-slot": 1.2.4
  "@radix-ui/react-switch": 1.2.6
  "@radix-ui/react-toggle": 1.1.10
  babel-plugin-react-compiler: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  fumadocs-core: 16.0.9
  fumadocs-mdx: 13.0.6
  fumadocs-ui: 16.0.9
  lefthook: 2.0.2
  lucide-react: 0.553.0
  next: 16.0.1
  postcss: 8.5.6
  react: 19.2.0
  react-dom: 19.2.0
  rimraf: 6.1.0
  server-only: 0.0.1
  shadcn: 3.5.0
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.17
  tailwindcss-animate: 1.0.7
  turbo: 2.6.0
  typescript: 5.9.3
  workflow: 4.0.1-beta.12
  zod: 4.1.12

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - lefthook
  - msw
  - prisma
  - protobufjs
  - puppeteer
  - sharp
