import '@/styles/globals.css';
import { fonts } from '@/fonts';
import { cn } from '@/lib/classnames';
import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: { default: 'Create Next App', template: '%s | Create Next App' },
  description: 'Generated by create next app',
};

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <html lang='en' className={cn(fonts)}>
      <body className='isolate'>{children}</body>
    </html>
  );
};

export default Layout;
