import { exec } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { rimraf } from 'rimraf';
import { registry } from '../registry/niv/index';

type RegistryFile = {
  path: string;
  type: string;
  target?: string;
};

type RegistryItem = {
  name: string;
  description?: string;
  type: string;
  registryDependencies?: Array<string>;
  files?: Array<RegistryFile>;
  categories?: Array<string>;
  meta?: Record<string, unknown>;
};

async function buildRegistryIndex() {
  let index = `
// biome-ignore-all lint/performance/noNamespaceImport: autogenerated file
// biome-ignore-all lint/suspicious/noExplicitAny: autogenerated file
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map(
      (file: RegistryFile) => `registry/niv/${file.path}`,
    );
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/niv/${item.files[0].path}`
      : '';

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ''}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file: RegistryFile) => {
      const filePath = `registry/niv/${typeof file === 'string' ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === 'string'
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ''}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object');
      return { default: mod.default || mod[exportName] }
    })`
        : 'null'
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), 'registry/__index__.tsx'));
  await fs.writeFile(path.join(process.cwd(), 'registry/__index__.tsx'), index);
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item: RegistryItem) => {
      const files = item.files?.map((file: RegistryFile) => {
        return {
          ...file,
          path: `registry/niv/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), 'registry.json'));
  await fs.writeFile(
    path.join(process.cwd(), 'registry.json'),
    JSON.stringify(fixedRegistry, null, 2),
  );

  // 3. Copy the registry.json to the public/r directory.
  await fs.cp(
    path.join(process.cwd(), 'registry.json'),
    path.join(process.cwd(), 'public/r/registry.json'),
    { recursive: true },
  );
}

async function buildRegistry() {
  return await new Promise((resolve, reject) => {
    const process = exec(
      'bunx --bun shadcn build registry.json --output public/r',
    );

    process.on('exit', code => {
      if (code === 0) {
        resolve(undefined);
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log('🗂️ Building registry/__index__.tsx...');
  await buildRegistryIndex();

  console.log('💅 Building registry.json...');
  await buildRegistryJsonFile();

  console.log('🏗️ Building registry...');
  await buildRegistry();

  console.log('✅ Registry build completed successfully!');
} catch (error) {
  console.error(error);
  process.exit(1);
}
